# Generated by Django 2.2 on 2020-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='см', max_length=50, verbose_name='Размер'),
        ),
    ]
