# Generated by Django 2.2 on 2020-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
