# Generated by Django 2.2 on 2020-09-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwauth', '0003_kwuser_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kwuser',
            options={'ordering': ['is_active', '-is_superuser', '-is_staff', 'username']},
        ),
    ]
