# Generated by Django 2.2.1 on 2020-09-20 10:18

from django.db import migrations, models
import kwauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('kwauth', '0004_auto_20200913_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kwuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=kwauth.models.get_activation_key_expired),
        ),
    ]
