# Generated by Django 2.2.1 on 2020-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwauth', '0006_kwuserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kwuser',
            options={'ordering': ['-is_active', '-is_superuser', '-is_staff', 'username']},
        ),
        migrations.AlterField(
            model_name='kwuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'мужской'), ('F', 'женский')], max_length=1, verbose_name='пол'),
        ),
    ]
